image: node:17-stretch

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm ci
            - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --verbose sharp
            - npm run-script build
      - step:
          name: Deploy
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/dev_domowa_pizza/'
                LOCAL_PATH: './public/*'
