image: node:16
clone:
  lfs: true

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          artifacts:
            - public/**
          script:
            - npm ci
            - npm install sharp
            - npm run-script build
      - step:
          name: Deploy
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/domowa_pizza/public/'
                LOCAL_PATH: 'public/*'
