image: node:16-alpine

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          script:
            - apk update && apk add --no-cache build-base vips-dev freetype-dev libpng-dev jpeg-dev libjpeg-turbo-dev
            - npm install
            - npm run-script build
      - step:
          name: Deploy
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/dev_domowa_pizza/'
                LOCAL_PATH: './public/*'
