image: node:16
clone:
  lfs: true

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
            - public
            - gatsby
          artifacts:
            - public/**
          script:
            - npm ci
            - npm run-script build
      - step:
          name: Deploy
          image: atlassian/pipelines-awscli
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/domowa_pizza/gatsby/'
                LOCAL_PATH: 'public/*'
#      - step:
#          name: Deploy
#          image: atlassian/pipelines-awscli
#          script:
#            - aws s3 sync public/ s3://${BUCKET}/ --cache-control 'public, max-age=3600'    --delete --exclude "*" --include "*.html"
#            - aws s3 sync public/ s3://${BUCKET}/ --cache-control 'public, max-age=2592000' --delete --include "*" --exclude "*.html"


definitions:
  caches:
    public: public/
    gatsby: .cache/