image: node:16
clone:
  lfs: true

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
            - public
            - gatsby
          artifacts:
            - public/**
          script:
            - npm ci
            - npm run-script build
      - step:
          name: Deploy
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync public/ s3://${BUCKET}/ --cache-control 'public, max-age=2592000' --delete --exclude "*" --include "*.jpg" --include "*.jpeg" --include "*.png"
            - aws s3 sync public/ s3://${BUCKET}/ --cache-control 'public, max-age=3600'    --delete --include "*" --exclude "*.jpg" --exclude "*.jpeg" --exclude "*.png"

definitions:
  caches:
    public: public/
    gatsby: .cache/