image: node:16
clone:
  lfs: true

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          variables:
            SHARP_IGNORE_GLOBAL_LIBVIPS: '1'
          script:
            - npm ci
            - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install sharp --verbose
            - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm run-script build
      - step:
          name: Deploy
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/dev_domowa_pizza/'
                LOCAL_PATH: './public/*'
