image: node:14-stretch

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          script:
            - apt update && apt upgrade && apt install libvips-dev libjpeg-dev libpng-dev -y
            # - apk update && apk add --no-cache build-base vips-dev freetype-dev libpng-dev jpeg-dev libjpeg-turbo-dev
            - npm ci
            - ls -al /opt/atlassian/pipelines/agent/build/src/components/BookPage/features/
            - pwd
            - npm run-script build
      - step:
          name: Deploy
          script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER:   'technologie'
                SERVER: 'domowa.pizza'
                REMOTE_PATH: 'web/dev_domowa_pizza/'
                LOCAL_PATH: './public/*'
